### PR TITLE
Add doc frame

### PR DESCRIPTION
**Pull request by florian-vuillemot**
Re use code base from https://github.com/aws-amplify/docs to generate static website from markdown doc.
Official README.md and assets are conserved.

`docs/docs` include an basic example to illustrate a part of the README.md.

### CODE REVIEW

**Comment by nathanagez** [comment]
Can we add first documentation samples ? 
Also, can you fix the ESLint job not passing please.

**Review by nathanagez — CHANGES_REQUESTED** [review]
Can we add first documentation samples ?
Also, can you fix the ESLint job not passing please.

**Comment by florian-vuillemot** [comment]
I put the docs folder in the the eslinterignore because all the code comes from an external repos and we just update markdown files.
I put the root README in the generated doc as a "Getting Started". 
 
amplify1
amplify2
amplify3

**Comment by nathanagez** [comment]
@florian-vuillemot here are my thoughts:

- Since it is a totally different architecture, what do you think of creating a second repository and move all `docs` folder inside this new repository ?

We could create a subdomain, for instance `docs.amplify-video-community.trackit.io` and keep the community website on `amplify-video-community.trackit.io` exactly like amplify currently does with his community website.

**Comment by nathanagez** [comment]
Really weird, I'm not able to display something
Screenshot 2021-05-19 at 08 17 28

**Comment by spaniernathan** [comment]
> We could create a subdomain, for instance `docs.amplify-video-community.trackit.io` and keep the community website on `amplify-video-community.trackit.io` exactly like amplify currently does with his community website.

I think this is a good idea !

**Comment by florian-vuillemot** [comment]
> Really weird, I'm not able to display something
> Screenshot 2021-05-19 at 08 17 28

Should be resolved now, I forgot a dependency

**Comment by florian-vuillemot** [comment]
Migrated in https://github.com/trackit/docs-amplify-video-community

**Pull request closed without merging**
